# Generated by Django 2.2.5 on 2022-03-28 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20220328_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Sellerr',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Outdoor', 'Outdoor'), ('Indoor', 'Indoor')], max_length=200),
        ),
    ]
